apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.webex: ""
    notifications.argoproj.io/subscribe.on-deployed.webex: ""
    notifications.argoproj.io/subscribe.on-health-degraded.webex: ""
    notifications.argoproj.io/subscribe.on-sync-failed.webex: ""
    notifications.argoproj.io/subscribe.on-sync-running.webex: ""
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .
    repoURL: https://github.com/Jenik27/k8demo.git
    targetRevision: main
