apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.argocd-webhook: ""
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: .
    repoURL: https://github.com/Jenik27/k8demo.git
    targetRevision: main
  notifications: 
    - name: argocd-webhook
      webhook:
        url: https://webexapis.com/v1/webhooks/incoming/Y2lzY29zcGFyazovL3VzL1dFQkhPT0svNmUyMjI5YjgtMjliYS00YTFkLWFkNzgtMDUyZjNkNGUwMjZk
        contentType: application/json
        data: |
          {
           "text": "Hello World, {{ .app.metadata.name }}"
          }
      when:
        sync: 
          status: '*'
        operation:
          status: '*'